### ISSUE TITLE
기능추가제안, 버그 제보

### ISSUE THREAD

**Issue by k6k71c** [Riey/EraTrans#3]
"々"  버그요. 인터넷 찾아보니까 꿀도르 사전이나 이지트랜스 버그라길래, 
이지트랜스 원래 있던 것, 꿀도르 사전, Cache.dat을 삭제하고
이지트랜스만 다시 깔아서 EmueraFramework 1.3.4나 EraTrans 3.2.1로 돌려도 "々" 버그가 있네요.
EmueraFramework 1.3.4랑 EraTrans 3.2.1 자체 버그인 것 같아요.

오래 전에 꿀도르 사전이랑 이지트랜스 깔고 사용하고 있었을 때도
EmueraFramework랑 EraTrans에서 이런 버그가 있었어요.

예를 들자면(그냥 이지트랜스만 깔린 상태)
원문 - 色々
이지트랜스 - 여러가지
EmueraFramework 1.3.4나 EraTrans 3.2.1 - 색々

원문 - 色々な
이지트랜스 - 다양한
EmueraFramework 1.3.4나 EraTrans 3.2.1 - 색々

원문 - 薄々
이지트랜스 - 희미하게
EmueraFramework 1.3.4나 EraTrans 3.2.1 - 박々

원문 - 徐々に
이지트랜스 - 서서히
EmueraFramework 1.3.4나 EraTrans 3.2.1 - 서々에

원문 - 日々
이지트랜스 - 날마다
EmueraFramework 1.3.4나 EraTrans 3.2.1 - 날々

위의 것처럼 이지트랜스에서는 정상번역인데 EmueraFramework 1.3.4나 EraTrans 3.2.1를 거치면 비정상번역으로 변해요.

EraTrans 사용해서 번역할 때,
자동번역 돌리면 色々랑 色々な가 똑같이 색々으로 번역돼서
일괄번역으로 수정하는데에도 한계가 있어요.
이 버그가 해결불가버그라면  々를 검색하기 쉽게 EraTrans에 일어원문검색 기능을 추가 해주시면 안되나요? 저 버그 때문에 일일히 확인해 가면서 번역수정하기 힘들어서요.
기능 추가 건의하는 김에 일괄번역창에 닫기 버튼 추가도 해주셨으면 좋겠어요.  Alt+F4로 닫을 수 있긴 하지만 처음 쓸 때는 몰라서 곤란했던 기억이 있네요.

**Comment by Riey** [comment]
https://github.com/Riey/EraTrans/releases/tag/3.3.0

수정됐습니다 원문검색은 만들기가 까다로워서 당장은 하기 힘드네요
